"""
balance_core.py
================
Core algorithms for the Eco-Smart Balancer.

This module implements the signal processing and imbalance solving
algorithms that will eventually run on the ESP32-S3 firmware.
Keeping it in pure NumPy / SciPy lets us validate the math on PC
before committing to silicon.

Physical model
--------------
A wheel is modelled as a rigid body rotating around its mandrel axis,
with two unbalance masses lying on two correction planes (inner / A
and outer / B) separated by the rim width L. Each unbalance mass
generates a centrifugal force at the rotation frequency that is
sensed by two accelerometers mounted on the bearing supports.

The relationship between unbalance phasors and sensor phasors is
linear at first harmonic, captured by a 2x2 complex influence matrix
K. Calibration identifies K from three reference launches; runtime
solving inverts K to extract the corrections.

References
----------
- Wowk, "Machinery Vibration: Balancing", McGraw-Hill, 1995
- ISO 1940-1:2003 "Balance quality requirements for rotors"
"""

from __future__ import annotations

from dataclasses import dataclass
import numpy as np
from scipy.signal import butter, sosfiltfilt, get_window


# =====================================================================
# Sensor model
# =====================================================================

# ADXL355 datasheet figures (typical)
ADXL355_NOISE_DENSITY_UG_RTHZ = 25.0      # µg / sqrt(Hz)
ADXL355_FULL_SCALE_G = 2.0
ADXL355_LSB_PER_G = 256000.0              # ±2g range, 20-bit signed

# For balancing applications we band-limit aggressively. The rotation
# frequency is ~4 Hz, so a 50 Hz analog/digital LPF is more than enough
# and dramatically reduces the integrated noise. ADXL355 supports this
# via its built-in IIR filter (HPF/LPF chain).
ADXL355_BANDWIDTH_HZ = 50.0

G_TO_MS2 = 9.80665


@dataclass(frozen=True)
class SensorConfig:
    """Configuration of a MEMS accelerometer chain."""
    noise_density_ug_rthz: float = ADXL355_NOISE_DENSITY_UG_RTHZ
    bandwidth_hz: float = ADXL355_BANDWIDTH_HZ
    full_scale_g: float = ADXL355_FULL_SCALE_G
    sample_rate_hz: float = 2000.0

    @property
    def noise_rms_g(self) -> float:
        """RMS noise integrated over the bandwidth."""
        return (self.noise_density_ug_rthz * 1e-6) * np.sqrt(self.bandwidth_hz)

    @property
    def noise_rms_ms2(self) -> float:
        return self.noise_rms_g * G_TO_MS2


# =====================================================================
# Mechanical model
# =====================================================================

@dataclass(frozen=True)
class WheelGeometry:
    """Geometry of the wheel under test."""
    mass_kg: float = 20.0
    radius_m: float = 0.35
    width_m: float = 0.15          # distance between correction planes
    rim_radius_m: float = 0.20     # where weights are applied


@dataclass(frozen=True)
class MachineGeometry:
    """Geometry of the balancer mechanics (sensor positions)."""
    sensor_a_offset_m: float = 0.05    # distance from plane A to sensor A
    sensor_b_offset_m: float = 0.20    # distance from plane B to sensor B
    bearing_stiffness_n_per_m: float = 5e6


# =====================================================================
# Forward model: imbalance -> sensor signal
# =====================================================================

def imbalance_force_amplitude(mass_g: float, radius_m: float,
                              omega_rad_s: float) -> float:
    """
    Centrifugal force amplitude generated by an unbalance mass.

    F = m * r * omega^2

    Parameters
    ----------
    mass_g : unbalance mass in grams (NB: grams, not kg)
    radius_m : radius of the unbalance position
    omega_rad_s : angular velocity in rad/s

    Returns
    -------
    Force magnitude in newtons.
    """
    return (mass_g * 1e-3) * radius_m * omega_rad_s ** 2


def transfer_K_default(machine: MachineGeometry,
                       wheel: WheelGeometry) -> np.ndarray:
    """
    Synthesise a default 2x2 complex influence matrix K for simulation.

    Physical model: the spindle is mounted on silent-blocks tuned below
    the launch frequency (typical ω0 ≈ 8 Hz vs launch at 4 Hz). At launch
    frequency the imbalance force is partly transmitted to the bearing
    supports where the accelerometers sit, with effective sensitivity of
    roughly 0.04–0.08 m/s² per Newton — typical for the class of
    machines in the 80–100 kg range (cf. measurements on commercial
    units like the Cormach MEC 810).

    Diagonal terms dominate (force on plane A produces strong response
    on sensor A); off-diagonal crosstalk is geometry-dependent and
    typically 25–40 % of the diagonal magnitude.
    """
    # Direct gains in (m/s²) per N — realistic for a 80–100 kg balancer
    # frame with sensors on bearing supports
    g_aa = 0.060
    g_bb = 0.058   # slight asymmetry between inner/outer bearing housings

    # Crosstalk (off-diagonal): force on B couples into sensor A through
    # the rigid spindle path
    crosstalk_ratio = 0.32
    g_ab = g_aa * crosstalk_ratio
    g_ba = g_bb * crosstalk_ratio

    # Phase shifts (deg) modelling structural dynamics. The diagonal
    # phase comes from damping; the off-diagonal comes from geometry
    # (the moment arm gives a 90° phase shift in the rigid-body limit).
    phase_aa, phase_bb = 0.0, 5.0
    phase_ab, phase_ba = 90.0, -90.0

    K = np.array([
        [g_aa * np.exp(1j * np.deg2rad(phase_aa)),
         g_ab * np.exp(1j * np.deg2rad(phase_ab))],
        [g_ba * np.exp(1j * np.deg2rad(phase_ba)),
         g_bb * np.exp(1j * np.deg2rad(phase_bb))],
    ], dtype=complex)
    return K


def generate_signal(weight_a_g: float, angle_a_deg: float,
                    weight_b_g: float, angle_b_deg: float,
                    rpm: float,
                    duration_s: float,
                    sensor_cfg: SensorConfig,
                    wheel: WheelGeometry,
                    machine: MachineGeometry,
                    K: np.ndarray | None = None,
                    realistic_noise: bool = False,
                    rng: np.random.Generator | None = None
                    ) -> tuple[np.ndarray, np.ndarray, np.ndarray]:
    """
    Synthesise sensor signals s_a(t), s_b(t) and encoder angle(t).

    Parameters
    ----------
    weight_*_g, angle_*_deg : imbalance description on planes A and B
    rpm : steady-state launch RPM
    duration_s : acquisition time
    realistic_noise : if True, add 25 Hz peak (compressor) and 1/f drift

    Returns
    -------
    s_a, s_b : sensor signals (m/s^2), shape (N,)
    angle_rad : encoder angle (rad), shape (N,)
    """
    rng = rng if rng is not None else np.random.default_rng()
    K = K if K is not None else transfer_K_default(machine, wheel)

    fs = sensor_cfg.sample_rate_hz
    n = int(duration_s * fs)
    t = np.arange(n) / fs

    omega = 2 * np.pi * rpm / 60.0

    # Imbalance phasors (complex) — represent F * exp(j*phi)
    f_a_amp = imbalance_force_amplitude(weight_a_g, wheel.rim_radius_m, omega)
    f_b_amp = imbalance_force_amplitude(weight_b_g, wheel.rim_radius_m, omega)
    F_a = f_a_amp * np.exp(1j * np.deg2rad(angle_a_deg))
    F_b = f_b_amp * np.exp(1j * np.deg2rad(angle_b_deg))

    # Sensor phasors via influence matrix
    F_vec = np.array([F_a, F_b])
    S_vec = K @ F_vec
    S_a, S_b = S_vec[0], S_vec[1]

    # Time-domain signals (taking real part of phasor * e^(j omega t))
    angle_rad = omega * t
    s_a = np.real(S_a * np.exp(1j * angle_rad))
    s_b = np.real(S_b * np.exp(1j * angle_rad))

    # Add noise
    noise_rms = sensor_cfg.noise_rms_ms2
    s_a += rng.normal(0, noise_rms, size=n)
    s_b += rng.normal(0, noise_rms, size=n)

    if realistic_noise:
        # 1/f drift (slow temperature)
        drift_a = np.cumsum(rng.normal(0, noise_rms * 0.1, size=n)) / np.sqrt(n)
        drift_b = np.cumsum(rng.normal(0, noise_rms * 0.1, size=n)) / np.sqrt(n)
        s_a += drift_a
        s_b += drift_b
        # 25 Hz peak (compressor in workshop) at ~3x noise floor amplitude
        compressor_amp = noise_rms * 3.0
        s_a += compressor_amp * np.sin(2 * np.pi * 25 * t + rng.uniform(0, 2*np.pi))
        s_b += compressor_amp * np.sin(2 * np.pi * 25 * t + rng.uniform(0, 2*np.pi))

    return s_a, s_b, angle_rad


# =====================================================================
# Signal processing
# =====================================================================

def bandpass_filter(signal: np.ndarray, fs: float,
                    f_lo: float, f_hi: float, order: int = 4) -> np.ndarray:
    """4th-order Butterworth bandpass, zero-phase via filtfilt."""
    sos = butter(order, [f_lo, f_hi], btype='band', fs=fs, output='sos')
    return sosfiltfilt(sos, signal)


def extract_first_harmonic(signal: np.ndarray, fs: float,
                           rpm: float, n_samples: int | None = None
                           ) -> complex:
    """
    Extract the complex phasor of the first rotation harmonic by
    point-DFT at the exact rotation frequency.

    This is equivalent to a single-bin DFT (Goertzel-style) and avoids
    the spectral leakage that affects FFT-bin extraction when the
    rotation frequency does not fall exactly on a bin center. Real
    balancing machines do something equivalent: they synchronously
    correlate the sensor signal with sin/cos references at the encoder
    frequency over an integer number of revolutions.

    Returns
    -------
    Complex phasor representing amplitude * exp(j*phase) such that the
    underlying signal is approximately Re(phasor * exp(j*omega*t)).
    """
    n = len(signal) if n_samples is None else min(len(signal), n_samples)

    # Use an integer number of full revolutions for the cleanest result
    f_rot = rpm / 60.0
    samples_per_rev = fs / f_rot
    n_revs = int(n // samples_per_rev)
    n_use = max(int(n_revs * samples_per_rev), int(samples_per_rev * 4))
    n_use = min(n_use, n)

    sig = signal[:n_use] - np.mean(signal[:n_use])
    t = np.arange(n_use) / fs
    omega = 2 * np.pi * f_rot

    # Synchronous demodulation:
    #   X = (2/N) * Σ s[n] * exp(-j*omega*t[n])
    # For s[n] = A*cos(omega*t + φ), X = A * exp(j*φ)
    ref = np.exp(-1j * omega * t)
    return (2.0 / n_use) * np.sum(sig * ref)


# =====================================================================
# Calibration: identify influence matrix K
# =====================================================================

@dataclass
class CalibrationData:
    """Sensor phasors from the three calibration launches."""
    s_zero: tuple[complex, complex]    # no trial weight
    s_trial_a: tuple[complex, complex] # 50 g on plane A
    s_trial_b: tuple[complex, complex] # 50 g on plane B
    trial_mass_g: float = 50.0
    trial_radius_m: float = 0.20
    trial_rpm: float = 240.0


def identify_K(cal: CalibrationData,
               wheel: WheelGeometry) -> np.ndarray:
    """
    Identify the 2x2 complex influence matrix from calibration.

    Math:
      Define D_a = sensor response with trial on A only (s_trial_a - s_zero)
      Then column 1 of K is D_a / F_a_trial
      Similarly column 2 of K is D_b / F_b_trial
    """
    s_zero_a, s_zero_b = cal.s_zero
    s_a_trial, s_b_trial = cal.s_trial_a   # trial mass on plane A
    s_a_trialB, s_b_trialB = cal.s_trial_b # trial mass on plane B

    omega = 2 * np.pi * cal.trial_rpm / 60.0
    F_trial = imbalance_force_amplitude(cal.trial_mass_g, cal.trial_radius_m,
                                        omega)
    # Trial weights placed at angle 0 -> phasor = F_trial + 0j
    F_phasor = F_trial + 0j

    # Differentials caused by trial weights
    D_a = np.array([s_a_trial - s_zero_a, s_b_trial - s_zero_b])
    D_b = np.array([s_a_trialB - s_zero_a, s_b_trialB - s_zero_b])

    # K columns
    col_a = D_a / F_phasor
    col_b = D_b / F_phasor
    return np.column_stack([col_a, col_b])


# =====================================================================
# Solving: extract imbalance from measured phasors
# =====================================================================

@dataclass
class ImbalanceResult:
    weight_a_g: float
    angle_a_deg: float
    weight_b_g: float
    angle_b_deg: float

    def __repr__(self):
        return (f"ImbalanceResult(A={self.weight_a_g:.2f}g @ "
                f"{self.angle_a_deg:.1f}°, "
                f"B={self.weight_b_g:.2f}g @ {self.angle_b_deg:.1f}°)")


def solve_imbalance(s_a_phasor: complex, s_b_phasor: complex,
                    K: np.ndarray,
                    wheel: WheelGeometry,
                    rpm: float,
                    s_zero: tuple[complex, complex] = (0+0j, 0+0j)
                    ) -> ImbalanceResult:
    """
    Invert the sensor phasors through K to recover unbalance phasors,
    then convert force phasors back to (mass, angle) pairs.
    """
    # Subtract zero (taring)
    s_vec = np.array([s_a_phasor - s_zero[0], s_b_phasor - s_zero[1]])

    # Solve linear system
    F_vec = np.linalg.solve(K, s_vec)
    F_a, F_b = F_vec

    # Convert force amplitude back to mass at the rim radius
    omega = 2 * np.pi * rpm / 60.0
    denom = wheel.rim_radius_m * omega ** 2  # F = m*r*w^2 -> m = F/(r*w^2)

    mass_a_kg = np.abs(F_a) / denom
    mass_b_kg = np.abs(F_b) / denom

    # The force vector points opposite to the correction location, but
    # by convention we report the imbalance position (where the mass IS),
    # which is the same direction as F itself in our forward model.
    angle_a = np.rad2deg(np.angle(F_a)) % 360.0
    angle_b = np.rad2deg(np.angle(F_b)) % 360.0

    return ImbalanceResult(
        weight_a_g=mass_a_kg * 1000.0,
        angle_a_deg=angle_a,
        weight_b_g=mass_b_kg * 1000.0,
        angle_b_deg=angle_b,
    )


# =====================================================================
# End-to-end pipeline
# =====================================================================

def run_pipeline(s_a: np.ndarray, s_b: np.ndarray,
                 fs: float, rpm: float,
                 K: np.ndarray,
                 wheel: WheelGeometry,
                 s_zero: tuple[complex, complex] = (0+0j, 0+0j)
                 ) -> ImbalanceResult:
    """Full processing chain: filter -> FFT -> solve."""
    f_rot = rpm / 60.0
    s_a_filt = bandpass_filter(s_a, fs, max(0.5, f_rot - 2), f_rot + 6)
    s_b_filt = bandpass_filter(s_b, fs, max(0.5, f_rot - 2), f_rot + 6)
    p_a = extract_first_harmonic(s_a_filt, fs, rpm)
    p_b = extract_first_harmonic(s_b_filt, fs, rpm)
    return solve_imbalance(p_a, p_b, K, wheel, rpm, s_zero)


def angular_error_deg(measured_deg: float, true_deg: float) -> float:
    """Smallest angular difference in degrees, in [-180, 180]."""
    d = (measured_deg - true_deg + 180.0) % 360.0 - 180.0
    return float(d)
